resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: docker.io/cdkbot/capi-bootstrap-provider-microk8s
  newName: docker.io/cdkbot/capi-bootstrap-provider-microk8s
  newTag: latest
