---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - microk8sconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - microk8sconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - bootstrap.cluster.x-k8s.io
  resources:
  - microk8sconfigs/status
  verbs:
  - get
  - patch
  - update
