name: cla-check

on:
  pull_request:
    branches: [main]

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA signed
        uses: beliaev-maksim/has-signed-canonical-cla@install_axios
