name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Retrieve build information
        id: build
        run: |
          echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            bootstrap-components.yaml
            metadata.yaml
          generate_release_notes: true
          draft: true
          prerelease: ${{ contains(steps.build.outputs.version, 'rc' }}
